language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - docker build -t testimage -f app/Dockerfile app/

script:
  # execute test
  - docker run testimage pytest

addons:
  artifacts:
    s3_region: "ap-northeast-1"
    paths:
      - ./app
    debug: true
    target-paths: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
    bucket: "travis-ci-artifacts-20191112"
